### ISSUE TITLE
bx::sqrt(0.f) will return NaN

### ISSUE THREAD

**Issue by junjie020** [bkaradzic/bx#299]
test code:
``` C++
float  r = bx::sqrt(0.f);
```

_r_ will be **_NaN_**

And I build a bx test cases and run, the result:

> 2023-04-17 10:42:36.368 test_bx[34092:3520110] ../../3rd/bx/tests/run_test.cpp(19): Compiler: Clang 14.0.3, CPU: ARM, Architecture: 64-bit, OS: OSX, CRT: Clang C Library, Date: Apr 17 2023, Time: 10:40:47, C++: C++17
> Randomness seeded to: 2449447446
> 
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> test_bx is a Catch2 v3.1.0 host application.
> Run with -? for options
> 
> -------------------------------------------------------------------------------
> libm
> -------------------------------------------------------------------------------
> ../../3rd/bx/tests/math_test.cpp:65
> ...............................................................................
> 
> ../../3rd/bx/tests/math_test.cpp:114: FAILED:
>   REQUIRE( bx::isEqual(bx::sqrt(xx), ::sqrtf(xx), 0.00001f) )
> with expansion:
>   false
> 
> 905.012000
> ===============================================================================
> test cases:      185 |      184 passed | 1 failed
> assertions: 11265218 | 11265217 passed | 1 failed
> 

That bug is relate to:
https://github.com/bkaradzic/bx/issues/298

**Comment by bkaradzic** [comment]
Can't repro:

```
==== Building bx (release) ====
==== Building bx.test (release) ====
math_test.cpp
Linking bx.test
Running...
2023-04-16 20:41:39.397 bx.testRelease[14422:366556] ../../../tests/run_test.cpp(19): Compiler: Clang 14.0.3, CPU: ARM, Architecture: 64-bit, OS: OSX, CRT: Clang C Library, Date: Apr 13 2023, Time: 20:32:22, C++: C++14
Filters: libm
Randomness seeded to: 3232557189
===============================================================================
All tests passed (579889 assertions in 1 test case)
```

**Comment by junjie020** [comment]
I want to know, how do you build bx.test target from bx?

Here is what I try to build bx.test taget from bx/makefile, like:
> cd _bxfolder_
> make test
> .build/osx-x64/bin/bx.testRelease

result:

> 2023-04-17 16:06:04.935 bx.testRelease[92617:3820883] ../../../tests/run_test.cpp(19): Compiler: Clang 14.0.3, CPU: x86, Architecture: 64-bit, OS: OSX, CRT: Clang C Library, Date: Apr 17 2023, Time: 15:26:31, C++: C++14
> Randomness seeded to: 3560497745
> 
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> bx.testRelease is a Catch2 v3.1.0 host application.
> Run with -? for options
> 
> -------------------------------------------------------------------------------
> isFinite, isInfinite, isNan
> -------------------------------------------------------------------------------
> ../../../tests/math_test.cpp:15
> ...............................................................................
> 
> ../../../tests/math_test.cpp:20: FAILED:
>   REQUIRE( std::isnan(u.f) == bx::isNan(u.f) )
> with expansion:
>   false == true
> 
> 903.920000
> -------------------------------------------------------------------------------
> Settings
> -------------------------------------------------------------------------------
> ../../../tests/settings_test.cpp:10
> ...............................................................................
> 
> ../../../tests/settings_test.cpp:10: FAILED:
>   {Unknown expression after the reported line}
> due to a fatal error condition:
>   SIGSEGV - Segmentation violation signal
> 
> ===============================================================================
> test cases:       35 |       33 passed | 2 failed
> assertions: 10154393 | 10154391 passed | 2 failed


It's different from last result which build from my build system. But still have some strange errors.

Could you mind to show me how you build your bx.test target? 

My test device is **macbook M1 with macOS Ventura 13.2.1**

Thanks.

**Comment by cloudwu** [comment]
I think https://github.com/bkaradzic/bx/blob/7bbda806d96ca55433f6d9857270360c05515fec/include/bx/inline/simd128_neon.inl#L655  `simd_rsqrt(0)` should be NaN here.

**Comment by bkaradzic** [comment]
Did you try with latest?

**Comment by junjie020** [comment]
I have try the new code(build from bx/makefile), all test passed.

Beside that, could you mind to define a macro, let the bx lib use the CRT version math methods?

**Comment by bkaradzic** [comment]
> Beside that, could you mind to define a macro, let the bx lib use the CRT version math methods?

Not in official repo,  I would suggest you just modify bx for your project to do whatever you need.

**Comment by junjie020** [comment]
I found it will failed the test with ARM architecture. To reproduce:
> cd _bxfolder_
> make osx-arm64-release
> ./.build/osx-arm64/bin/bx.testRelease

It will log:

>
> 2023-04-25 10:19:16.197 bx.testRelease[7498:1704298] ../../../tests/run_test.cpp(19): Compiler: Clang 14.0.3, CPU: ARM, Architecture: 64-bit, OS: OSX, CRT: Clang C Library, Date: Apr 25 2023, Time: 10:18:31, C++: C++14
Randomness seeded to: 2004761687
>
> bx.testRelease is a Catch2 v3.1.0 host application.
> Run with -? for options
>
> libm
> ../../../tests/math_test.cpp:75
>
> ../../../tests/math_test.cpp:158: FAILED:
>  REQUIRE( bx::isNan(bx::sqrtRef(-1.0f) ) )
> with expansion:
>  false

> 905.025000
> test cases:      185 |      184 passed | 1 failed
> assertions: 11271229 | 11271228 passed | 1 failed

**Comment by bkaradzic** [comment]
> I found it will failed the test with ARM architecture. To reproduce:

But your original problem is solved? This is `sqrtRef` failure which is not used by default... I'll fix it, just asking for original issue?

**Comment by junjie020** [comment]
I try to reproduce my original problem, it can pass the test in release version, but it still failed in debug version.

> cd _bxfolder_
> make osx-arm64-debug 
> /.build/osx-arm64/bin/bx.testDebug  


> 2023-04-25 10:53:00.302 bx.testDebug[9366:1716925] ../../../tests/run_test.cpp(19): Compiler: Clang 14.0.3, CPU: ARM, Architecture: 64-bit, OS: OSX, CRT: Clang C Library, Date: Apr 25 2023, Time: 10:51:01, C++: C++14
Randomness seeded to: 1175618260

> bx.testDebug is a Catch2 v3.1.0 host application.
> Run with -? for options

> libm
> ../../../tests/math_test.cpp:75
>
> ../../../tests/math_test.cpp:115: FAILED:
>  REQUIRE( bx::isInfinite(bx::rsqrt(0.0f) ) )
> with expansion:
>  false

> 905.026000
> test cases:      185 |      184 passed | 1 failed
> assertions: 11263216 | 11263215 passed | 1 failed

**Comment by bkaradzic** [comment]
Try again with latest.
